package Interfaz;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author nacho
 */
public class AltaPostulante2 extends javax.swing.JPanel {

    /**
     * Creates new form AltaPostulante2
     */
    public AltaPostulante2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboTema = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        botonAgregar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        scrollExperiencias = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tema:");
        add(jLabel1);
        jLabel1.setBounds(30, 20, 37, 15);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("NIvel:");
        add(jLabel2);
        jLabel2.setBounds(30, 60, 34, 15);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Experiencia:");
        add(jLabel3);
        jLabel3.setBounds(30, 120, 73, 15);

        comboTema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTemaActionPerformed(evt);
            }
        });
        add(comboTema);
        comboTema.setBounds(127, 19, 260, 23);
        add(jSpinner1);
        jSpinner1.setBounds(127, 62, 87, 16);

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        add(botonAgregar);
        botonAgregar.setBounds(232, 59, 87, 23);

        botonEliminar.setText("Eliminar");
        add(botonEliminar);
        botonEliminar.setBounds(18, 153, 90, 23);

        botonCancelar.setText("Cancelar");
        add(botonCancelar);
        botonCancelar.setBounds(20, 230, 90, 23);

        botonRegistrar.setText("Registrar");
        add(botonRegistrar);
        botonRegistrar.setBounds(300, 230, 90, 23);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollExperiencias.setViewportView(jList1);

        add(scrollExperiencias);
        scrollExperiencias.setBounds(136, 123, 250, 73);
    }// </editor-fold>//GEN-END:initComponents

    private void comboTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTemaActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JComboBox<String> comboTema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JScrollPane scrollExperiencias;
    // End of variables declaration//GEN-END:variables
}
