/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

/**
 *
 * @author nacho
 */
public class consultaPuestos extends javax.swing.JPanel {

    /**
     * Creates new form consultaPuestos
     */
    public consultaPuestos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Puestos = new javax.swing.JLabel();
        panelPuestos = new javax.swing.JScrollPane();
        listaPuestos = new javax.swing.JList<>();
        spinNivel = new javax.swing.JSpinner();
        labelNivel = new javax.swing.JLabel();
        botonConsultar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelPostulantes = new javax.swing.JScrollPane();
        listPostulantes = new javax.swing.JList<>();
        botonCancelar = new javax.swing.JButton();
        botonExportar = new javax.swing.JButton();

        setLayout(null);

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo.setText("Consulta para puesto");
        add(Titulo);
        Titulo.setBounds(100, 10, 210, 20);

        Puestos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Puestos.setText("Puestos:");
        add(Puestos);
        Puestos.setBounds(20, 40, 70, 15);

        listaPuestos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        panelPuestos.setViewportView(listaPuestos);

        add(panelPuestos);
        panelPuestos.setBounds(20, 60, 360, 154);
        add(spinNivel);
        spinNivel.setBounds(120, 240, 100, 20);

        labelNivel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNivel.setText("Nivel:");
        add(labelNivel);
        labelNivel.setBounds(20, 240, 34, 15);

        botonConsultar.setText("Consultar");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });
        add(botonConsultar);
        botonConsultar.setBounds(290, 240, 90, 23);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Postulantes:");
        add(jLabel4);
        jLabel4.setBounds(20, 290, 90, 15);

        listPostulantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        panelPostulantes.setViewportView(listPostulantes);

        add(panelPostulantes);
        panelPostulantes.setBounds(20, 310, 360, 154);

        botonCancelar.setText("Cancelar");
        add(botonCancelar);
        botonCancelar.setBounds(20, 480, 90, 23);

        botonExportar.setText("Exportar");
        botonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExportarActionPerformed(evt);
            }
        });
        add(botonExportar);
        botonExportar.setBounds(310, 480, 79, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void botonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Puestos;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonExportar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JList<String> listPostulantes;
    private javax.swing.JList<String> listaPuestos;
    private javax.swing.JScrollPane panelPostulantes;
    private javax.swing.JScrollPane panelPuestos;
    private javax.swing.JSpinner spinNivel;
    // End of variables declaration//GEN-END:variables
}
