/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

/**
 *
 * @author nacho
 */
public class HistorialPostulante extends javax.swing.JPanel {

    /**
     * Creates new form HistorialPostulante
     */
    public HistorialPostulante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelPostulantes = new javax.swing.JScrollPane();
        listPostulantes = new javax.swing.JList<>();
        panelExperiencia = new javax.swing.JScrollPane();
        listExperiencia = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        textBuscar = new javax.swing.JTextField();
        botonReset = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonSalir = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Historial de postulante");
        add(jLabel1);
        jLabel1.setBounds(300, 10, 240, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");
        jLabel2.setAlignmentY(0.0F);
        add(jLabel2);
        jLabel2.setBounds(410, 70, 100, 15);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Cedula:");
        jLabel3.setAlignmentY(0.0F);
        add(jLabel3);
        jLabel3.setBounds(410, 100, 100, 15);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Direccion:");
        jLabel4.setAlignmentY(0.0F);
        add(jLabel4);
        jLabel4.setBounds(410, 130, 100, 15);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Telefono:");
        jLabel5.setAlignmentY(0.0F);
        add(jLabel5);
        jLabel5.setBounds(410, 160, 100, 15);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mail:");
        jLabel6.setAlignmentY(0.0F);
        add(jLabel6);
        jLabel6.setBounds(410, 190, 100, 15);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Postulantes:");
        add(jLabel7);
        jLabel7.setBounds(20, 60, 90, 15);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Experiencia:");
        jLabel8.setAlignmentY(0.0F);
        add(jLabel8);
        jLabel8.setBounds(410, 280, 100, 15);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Linkedin:");
        jLabel9.setAlignmentY(0.0F);
        add(jLabel9);
        jLabel9.setBounds(410, 220, 100, 15);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Formato:");
        jLabel10.setAlignmentY(0.0F);
        add(jLabel10);
        jLabel10.setBounds(410, 250, 100, 15);

        listPostulantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        panelPostulantes.setViewportView(listPostulantes);

        add(panelPostulantes);
        panelPostulantes.setBounds(20, 80, 300, 300);

        listExperiencia.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        panelExperiencia.setViewportView(listExperiencia);

        add(panelExperiencia);
        panelExperiencia.setBounds(510, 280, 280, 110);

        jLabel11.setText("Buscar:");
        add(jLabel11);
        jLabel11.setBounds(20, 420, 45, 17);

        textBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscarActionPerformed(evt);
            }
        });
        add(textBuscar);
        textBuscar.setBounds(80, 420, 270, 23);

        botonReset.setText("Resetear");
        botonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetActionPerformed(evt);
            }
        });
        add(botonReset);
        botonReset.setBounds(470, 420, 90, 23);

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        add(botonBuscar);
        botonBuscar.setBounds(380, 420, 72, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro", "Evaluador", "Puntaje", "Comentarios"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        add(jScrollPane3);
        jScrollPane3.setBounds(20, 460, 830, 190);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        add(botonSalir);
        botonSalir.setBounds(20, 680, 72, 23);
        add(jTextField1);
        jTextField1.setBounds(510, 240, 280, 23);
        add(jTextField2);
        jTextField2.setBounds(510, 210, 280, 23);
        add(jTextField3);
        jTextField3.setBounds(510, 180, 280, 23);
        add(jTextField4);
        jTextField4.setBounds(510, 150, 280, 23);
        add(jTextField5);
        jTextField5.setBounds(510, 120, 280, 23);
        add(jTextField6);
        jTextField6.setBounds(510, 90, 280, 23);
        add(jTextField7);
        jTextField7.setBounds(510, 60, 280, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void textBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscarActionPerformed

    private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonResetActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonReset;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JList<String> listExperiencia;
    private javax.swing.JList<String> listPostulantes;
    private javax.swing.JScrollPane panelExperiencia;
    private javax.swing.JScrollPane panelPostulantes;
    private javax.swing.JTextField textBuscar;
    // End of variables declaration//GEN-END:variables
}
