/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

/**
 *
 * @author nacho
 */
public class menu extends javax.swing.JPanel {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemRegistroTematica = new javax.swing.JMenuItem();
        menuItemAltaPostulante = new javax.swing.JMenuItem();
        menuItemBajaPostulante = new javax.swing.JMenuItem();
        menuItemREgistroEvaluador = new javax.swing.JMenuItem();
        menuItemIngresoEntrevista = new javax.swing.JMenuItem();
        menuItemRegistroPuesto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemConsultaPuesto = new javax.swing.JMenuItem();
        menuItemHistorialPostulante = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        TituloMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("Registro");

        menuItemRegistroTematica.setText("Registro tematica");
        menuItemRegistroTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistroTematicaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRegistroTematica);

        menuItemAltaPostulante.setText("Alta postulante");
        jMenu1.add(menuItemAltaPostulante);

        menuItemBajaPostulante.setText("Baja posutlante");
        jMenu1.add(menuItemBajaPostulante);

        menuItemREgistroEvaluador.setText("Registro evaluador");
        jMenu1.add(menuItemREgistroEvaluador);

        menuItemIngresoEntrevista.setText("Ingresdo entrevista");
        jMenu1.add(menuItemIngresoEntrevista);

        menuItemRegistroPuesto.setText("Registro puesto");
        jMenu1.add(menuItemRegistroPuesto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");

        menuItemConsultaPuesto.setText("Consulta puesto");
        menuItemConsultaPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaPuestoActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemConsultaPuesto);

        menuItemHistorialPostulante.setText("Historial postulante");
        menuItemHistorialPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHistorialPostulanteActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemHistorialPostulante);

        jMenuItem2.setText("Consulta tematica");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setLayout(null);

        TituloMenu.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        TituloMenu.setText("Bienvenidos a ETCHUNIN:");
        add(TituloMenu);
        TituloMenu.setBounds(10, 30, 240, 30);

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel1.setText("Sistema para la gestion de postulantes llamados a puestos de trabajo.");
        add(jLabel1);
        jLabel1.setBounds(10, 60, 540, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuItemHistorialPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHistorialPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemHistorialPostulanteActionPerformed

    private void menuItemConsultaPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemConsultaPuestoActionPerformed

    private void menuItemRegistroTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistroTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemRegistroTematicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuItemAltaPostulante;
    private javax.swing.JMenuItem menuItemBajaPostulante;
    private javax.swing.JMenuItem menuItemConsultaPuesto;
    private javax.swing.JMenuItem menuItemHistorialPostulante;
    private javax.swing.JMenuItem menuItemIngresoEntrevista;
    private javax.swing.JMenuItem menuItemREgistroEvaluador;
    private javax.swing.JMenuItem menuItemRegistroPuesto;
    private javax.swing.JMenuItem menuItemRegistroTematica;
    // End of variables declaration//GEN-END:variables
}
