package interfaz;

import dominio.*;
import dominio.Tematica;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

public class VentanaRegistroPuesto extends javax.swing.JFrame {

    private Sistema sistema;

    public VentanaRegistroPuesto(Sistema sistema) {
        initComponents();
        this.sistema = sistema;

        ArrayList<Tematica> temas = this.sistema.getTematicas();

        for (Tematica elem : temas) {
            System.out.println(elem.toString());
            JCheckBox checkbox = new JCheckBox(elem.toString());
            panelTemas.add(checkbox);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoFormato = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        scrollTemas = new javax.swing.JScrollPane();
        panelTemas = new javax.swing.JPanel();
        radioRemoto = new javax.swing.JRadioButton();
        radioPresencial = new javax.swing.JRadioButton();
        radioMixto = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Registro Puesto");
        Titulo.setAlignmentY(0.0F);
        getContentPane().add(Titulo);
        Titulo.setBounds(102, 6, 210, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 70, 15);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Formato:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 90, 70, 15);

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        getContentPane().add(textNombre);
        textNombre.setBounds(100, 60, 240, 23);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Temas Requeridos:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 118, 15);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar);
        botonCancelar.setBounds(40, 220, 90, 23);

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistrar);
        botonRegistrar.setBounds(250, 220, 90, 23);

        scrollTemas.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelTemas.setLayout(new java.awt.GridLayout(0, 1));
        scrollTemas.setViewportView(panelTemas);

        getContentPane().add(scrollTemas);
        scrollTemas.setBounds(150, 130, 190, 80);

        GrupoFormato.add(radioRemoto);
        radioRemoto.setText("Remoto");
        radioRemoto.setAlignmentY(0.0F);
        getContentPane().add(radioRemoto);
        radioRemoto.setBounds(100, 90, 80, 30);

        GrupoFormato.add(radioPresencial);
        radioPresencial.setText("Presencial");
        radioPresencial.setAlignmentY(0.0F);
        radioPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPresencialActionPerformed(evt);
            }
        });
        getContentPane().add(radioPresencial);
        radioPresencial.setBounds(180, 90, 90, 30);

        GrupoFormato.add(radioMixto);
        radioMixto.setText("Mixto");
        radioMixto.setAlignmentY(0.0F);
        radioMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMixtoActionPerformed(evt);
            }
        });
        getContentPane().add(radioMixto);
        radioMixto.setBounds(280, 90, 70, 30);

        setBounds(0, 0, 430, 294);
    }// </editor-fold>//GEN-END:initComponents

    private void radioPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPresencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPresencialActionPerformed

    private void radioMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMixtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMixtoActionPerformed

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        String nombrePuesto = textNombre.getText();
        ArrayList<Puesto> listaDePuestos = sistema.getPuestos();
        boolean valido = true;
        if(!nombrePuesto.equals("")){
            for (Puesto elem : listaDePuestos) {
                if (nombrePuesto.equals(elem.getNombres())) {
                    valido = false;
                    break;
                }
            }
        }else{
            valido = false;
        }
        String formato = "";
        if (radioMixto.isSelected()) {
            formato = "Mixto";
        } else if (radioPresencial.isSelected()) {
            formato = "Presencial";
        } else if (radioRemoto.isSelected()) {
            formato = "Remoto";
        }

        Component[] components = panelTemas.getComponents();
        ArrayList<String> temasSeleccionados = new ArrayList<>();
        boolean hayTemas = false;
        for (Component component : components) {
            if (component instanceof JCheckBox) {
                JCheckBox checkbox = (JCheckBox) component;
                if (checkbox.isSelected()) {
                    temasSeleccionados.add(checkbox.getText());
                    hayTemas = true;
                }
            }
        }
        String[] temas = temasSeleccionados.toArray(new String[0]);
        if (hayTemas) {
            if (valido) {
                Puesto puesto = new Puesto(nombrePuesto, formato, temas);
                sistema.getPuestos().add(puesto);
                JOptionPane.showMessageDialog(this, "El puesto ha sido ingresado correctamente");
                sistema.limpiarCamposField(textNombre);
                sistema.eliminarCheckBox(panelTemas);
                GrupoFormato.clearSelection();

            } else {
                JOptionPane.showMessageDialog(this, "Error con el nombre, intente con otro");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No selecciono temas para el puesto");
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sistema sistema = new Sistema();
                new VentanaRegistroPuesto(sistema).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoFormato;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelTemas;
    private javax.swing.JRadioButton radioMixto;
    private javax.swing.JRadioButton radioPresencial;
    private javax.swing.JRadioButton radioRemoto;
    private javax.swing.JScrollPane scrollTemas;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
